### ISSUE TITLE
Can't get this to work 😢 (ENOENT)

### ISSUE THREAD

**Issue by Haroenv** [xtuc/c-webpack-demo#1]
When running `webpack -w` I get obscure errors: 

```
 /Users/haroen/git/c-webpack-demo/node_modules/.bin/webpack -w

Webpack is watching the files…

Hash: 90a3000d5e74cf3163a9
Version: webpack 4.8.3
Time: 343ms
Built at: 2018-05-23 17:54:12
 2 assets
Entrypoint main = bundle.js
[0] ./src/index.js 88 bytes {1} [built]
[1] ./src/add.c 339 bytes {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/add.c
Module build failed: Error: spawnSync ./node_modules/.bin/holyc ENOENT
    at Object.spawnSync (internal/child_process.js:967:20)
    at spawnSync (child_process.js:581:24)
    at execFileSync (child_process.js:609:13)
    at Object.module.exports (/Users/haroen/git/c-webpack-demo/node_modules/holyc/loader.js:7:3)
 @ ./src/index.js 1:0-17

ERROR in chunk 0
0.bundle.js
/Users/haroen/git/c-webpack-demo/node_modules/holyc/loader.js!/Users/haroen/git/c-webpack-demo/src/add.c
unexpected end
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] (webpack)/buildin/module.js 519 bytes {0} [built]
    [1] (webpack)/buildin/global.js 509 bytes {0} [built]
        + 2 hidden modules
```

I have `clang` installed on my computer, maybe something with no `index.html` here?

**Comment by Haroenv** [comment]
Didn't change if I added an `index.html` in root or in `/src`

**Comment by xtuc** [comment]
did you run npm i?

**Comment by Haroenv** [comment]
Yep, I installed the dependencies (with yarn), and used `yarn webpack -w` to use the local version

**Comment by xtuc** [comment]
What happens when you run `./node_modules/.bin/holyc src/add.c`?

**Comment by Haroenv** [comment]
```
Failed to execute process './node_modules/.bin/holyc'. Reason:
The file './node_modules/.bin/holyc' specified the interpreter '/usr/bin/node', which is not an executable command.
```

Seems like my node is not in `/usr/bin/node`, but rather in `/Users/haroen/.nvm/versions/node/v10.0.0/bin/node`. I think we can either use `#!/usr/bin/env node`

Can replicate that in a small demo file too, will do a PR on `holyc`

**Comment by xtuc** [comment]
Ah my bad sorry. That would be great if you can send a PR for that :+1:
